apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: hip-motion
  namespace: flux-system
spec:
  interval: 1m
  dependsOn:
    - name: clusterinfra
    - name: secrets
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./tenants/SolaRentals/hip-motion
  prune: true
  validation: client
