apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../infra/namespace_infra
  - ../../../hip/
  - namespace.yaml
patches:
  - path: hip-values.yaml
    target:
      kind: HelmRelease
      name: hip
  - path: redis.yaml
    target:
      kind: Pod
      name: redis
namespace: motion
