apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../infra/monitoring_infra
  - ../../../infra/monitoring_infra/pushgateway
patches:
  - path: redis-exporter-values.yaml
    target:
      kind: HelmRelease
      name: prometheus-redis-exporter
  - path: pushgateway-values.yaml
    target:
      kind: HelmRelease
      name: pushgateway
namespace: monitoring
