name: Trigger Jenkins Appliance Phase 2 job

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  trigger-phase2:
    if: >
      github.event.pull_request.merged == true &&
      contains(github.event.pull_request.title, 'automated-pr') &&
      contains(github.event.pull_request.labels.*.name, 'chore') &&
      startsWith(github.event.pull_request.head.ref, 'deployment/appliance/')
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          separator: "\n"

      - name: Check for hip-motion file changes
        id: check-hip-files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            if [[ "$file" == tenants/*/hip-motion/kustomization.yaml || "$file" == tenants/*/hip-motion/hip-values.yaml ]]; then
              echo "MATCH_FOUND=true" >> $GITHUB_ENV
              exit 0
            fi
          done
          echo "MATCH_FOUND=false" >> $GITHUB_ENV

      - name: Trigger Jenkins job
        if: env.MATCH_FOUND == 'true'
        run: |
          curl -X POST "$JENKINS_URL/view/alljob/trigger-phase2-test/build" \
            --user "$JENKINS_USER:$JENKINS_API_TOKEN"

        