name: Trigger Jenkins Appliance Phase 2 job

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  trigger-phase2:
    if: >
      github.event.pull_request.merged == true &&
      contains(github.event.pull_request.title, 'Automated PR for Appliance Tenant') &&
      contains(github.event.pull_request.labels.*.name, 'new_deployment') &&
      startsWith(github.event.pull_request.head.ref, 'deployment/appliance/')
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          separator: "\n"

      - name: Check for hip-motion file changes
        id: check-hip-files
        run: |
          echo "Changed files raw output:"
          echo "${{ steps.changed-files.outputs.all_changed_files }}"

          MATCH_FOUND=false

          readarray -t changed_files <<< "${{ steps.changed-files.outputs.all_changed_files }}"

          for file in "${changed_files[@]}"; do
            echo "Checking file: $file"
            if [[ "$file" == tenants/*/hip-motion/kustomization.yaml || "$file" == tenants/*/hip-motion/hip-values.yaml ]]; then
              echo "Match found: $file"
              MATCH_FOUND=true
              break
            fi
          done

          echo "MATCH_FOUND=$MATCH_FOUND" >> $GITHUB_ENV



      - name: Extract tenant info from YAML in PR body
        if: env.MATCH_FOUND == 'true'
        run: |
          echo "${{ github.event.pull_request.body }}" > pr_body.yaml

          export TENANT_ID=$(yq '.Tenant_ID' pr_body.yaml)
          export TENANT_NAME=$(yq '.Tenant_Name' pr_body.yaml)
          export HOSTNAME_PREFIX=$(yq '.Hostname_Prefix' pr_body.yaml)

          echo "TENANT_ID=$TENANT_ID" >> $GITHUB_ENV
          echo "TENANT_NAME=$TENANT_NAME" >> $GITHUB_ENV
          echo "HOSTNAME_PREFIX=$HOSTNAME_PREFIX" >> $GITHUB_ENV

      - name: Trigger Jenkins job
        id: trigger_jenkins
        if: env.MATCH_FOUND == 'true'
        continue-on-error: true 
        env:
          JENKINS_URL: ${{ vars.JENKINS_URL }}
          JENKINS_USER: ${{ vars.JENKINS_USER }}
          JENKINS_API_TOKEN: ${{ secrets.JENKINS_API_TOKEN }}
        run: |
          echo "Triggering Jenkins job"
          HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" -X POST "$JENKINS_URL/view/all/job/trigger-phase2-test/buildWithParameters" \
            --user "$JENKINS_USER:$JENKINS_API_TOKEN" \
            --data "Tenant_ID=$TENANT_ID" \
            --data "Tenant_Name=$TENANT_NAME" \
            --data "Hostname_Prefix=$HOSTNAME_PREFIX")

      - name: Send Slack Success Notification
        if: steps.trigger_jenkins.outcome == 'success'
        uses: act10ns/slack@v2
        with:
          webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
          message: "✅ Successfully triggered Phase 2 deployment for tenant : *${{ env.TENANT_NAME }}*"
          status: success

      - name: Send Slack Failure Notification
        if: failure() && steps.trigger_jenkins.outcome == 'failure'
        uses: act10ns/slack@v2
        with:
          webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
          message: "❌ Failed to trigger Phase 2 deployment for tenant: *${{ env.TENANT_NAME }}*"
          status: failure









  